//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.imovel = new HashSet<imovel>();
            this.especializacao = new HashSet<especializacao>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<imovel> imovel { get; set; }
        public virtual ICollection<especializacao> especializacao { get; set; }
    }
}
