//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.endereco = new HashSet<endereco>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdState { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<endereco> endereco { get; set; }
    }
}
