//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.visita = new HashSet<visita>();
            this.imovel = new HashSet<imovel>();
            this.imovel1 = new HashSet<imovel>();
        }
    
        public int id { get; set; }
        public Nullable<int> idpessoa { get; set; }
        public string pendencia { get; set; }
    
        public virtual ICollection<visita> visita { get; set; }
        public virtual ICollection<imovel> imovel { get; set; }
        public virtual pessoa pessoa { get; set; }
        public virtual ICollection<imovel> imovel1 { get; set; }
    }
}
