//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class corretor
    {
        public corretor()
        {
            this.visita = new HashSet<visita>();
            this.especializacao = new HashSet<especializacao>();
        }
    
        public int id { get; set; }
        public Nullable<int> idpessoa { get; set; }
        public Nullable<int> vendasrealizadas { get; set; }
        public Nullable<decimal> vendasvalor { get; set; }
    
        public virtual ICollection<visita> visita { get; set; }
        public virtual pessoa pessoa { get; set; }
        public virtual ICollection<especializacao> especializacao { get; set; }
    }
}
