//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public endereco()
        {
            this.imovel = new HashSet<imovel>();
            this.pessoa = new HashSet<pessoa>();
        }
    
        public int id { get; set; }
        public string logradouro { get; set; }
        public Nullable<int> numero { get; set; }
        public int cidade { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<imovel> imovel { get; set; }
        public virtual ICollection<pessoa> pessoa { get; set; }
    }
}
