//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImobGentilEntities : DbContext
    {
        public ImobGentilEntities()
            : base("name=ImobGentilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<locacoes> locacoes { get; set; }
        public DbSet<pagamentos> pagamentos { get; set; }
        public DbSet<vendas> vendas { get; set; }
        public DbSet<visita> visita { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<endereco> endereco { get; set; }
        public DbSet<imagem> imagem { get; set; }
        public DbSet<imovel> imovel { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<corretor> corretor { get; set; }
        public DbSet<permissoes> permissoes { get; set; }
        public DbSet<pessoa> pessoa { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<especializacao> especializacao { get; set; }
        public DbSet<interesse> interesse { get; set; }
    }
}
