//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class interesse
    {
        public int id { get; set; }
        public Nullable<int> idimovel { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string status { get; set; }
        public Nullable<int> idcliente { get; set; }
    
        public virtual imovel imovel { get; set; }
        public virtual pessoa pessoa { get; set; }
    }
}
