//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class locacoes
    {
        public locacoes()
        {
            this.pagamentos = new HashSet<pagamentos>();
        }
    
        public int id { get; set; }
        public int idvisita { get; set; }
        public string status { get; set; }
        public string diapagamento { get; set; }
        public Nullable<System.DateTime> datalocacao { get; set; }
    
        public virtual visita visita { get; set; }
        public virtual ICollection<pagamentos> pagamentos { get; set; }
    }
}
