//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.permissoes = new HashSet<permissoes>();
        }
    
        public int id { get; set; }
        public Nullable<int> idpessoa { get; set; }
        public string usuario1 { get; set; }
        public string senha { get; set; }
    
        public virtual ICollection<permissoes> permissoes { get; set; }
        public virtual pessoa pessoa { get; set; }
    }
}
