//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class visita
    {
        public visita()
        {
            this.locacoes = new HashSet<locacoes>();
            this.vendas = new HashSet<vendas>();
        }
    
        public int id { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<int> idcorretor { get; set; }
        public Nullable<int> idimovel { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string resultado { get; set; }
        public string status { get; set; }
        public string hora { get; set; }
        public Nullable<decimal> corretorcomissao { get; set; }
    
        public virtual ICollection<locacoes> locacoes { get; set; }
        public virtual ICollection<vendas> vendas { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual corretor corretor { get; set; }
        public virtual imovel imovel { get; set; }
    }
}
